### PR TITLE
Fixed TCS permissions for Windows

### LINKED ISSUE #146: Fix TCS permissions for Windows

### PR DESCRIPTION
**Pull request by parthsane**
Removed the wrong check in the `add` function in enclaveapi sgxs-loader
Added a check in CanonicalSgxsReader to ensure that the TCS Page does not have any page permission flags set

Closes #146

### CODE REVIEW

File: sgxs-loaders/src/enclaveapi/mod.rs [hunk 1]
```diff
@@ -133,10 +133,8 @@ impl EnclaveLoad for WinInnerLibrary {
         match PageType::try_from(eadd.secinfo.flags.page_type()) {
             Ok(PageType::Reg) => {}
             Ok(PageType::Tcs) => {
-                if !eadd.secinfo.flags.contains(SecinfoFlags::R) {
-                    return Err(Error::Add(ErrorKind::InvalidInput.into()));
-                }
-                // NOTE: For some reason the windows API needs the Read flag set but then removes it while calling EADD
+                // NOTE: For some reason the windows API needs the PAGE_READWRITE set
+                // but the sgx EADD removes it
                 flags |= PAGE_ENCLAVE_THREAD_CONTROL | PAGE_READWRITE;
```
Comment (jethrogb) [inline sgxs-loaders/src/enclaveapi/mod.rs]: Use `flags =` to avoid including permission bits, if any.

File: sgxs/src/sgxs.rs [hunk 2]
```diff
@@ -19,6 +19,8 @@ pub enum Error {
     InvalidPageOffset,
     #[fail(display = "An unsized stream was encountered but a sized stream was expected.")]
     StreamUnsized,
+    #[fail(display = "Invalid Page Permissions {:?}",_0)]
+    InvalidPagePermission(SecinfoFlags),
```
Comment (jethrogb) [inline sgxs/src/sgxs.rs]: Don't add this

File: sgxs/src/sgxs.rs [hunk 3]
```diff
@@ -271,6 +273,11 @@ impl<'a, R: SgxsRead + 'a> SgxsRead for CanonicalSgxsReader<'a, R> {
                 {
                     return Err(Error::StreamNotCanonical.into());
                 }
+                if header.secinfo.flags.page_type() == PageType::Tcs as u8
+                    && header.secinfo.flags.intersects(SecinfoFlags::R|SecinfoFlags::W|SecinfoFlags::X)
+                {
+                    return Err(Error::InvalidPagePermission(header.secinfo.flags).into())
```
Comment (jethrogb) [inline sgxs/src/sgxs.rs]: Just retrun `StreamNotCanonical`

**Comment by parthsane** [comment]
@jethrogb I've force pushed the commit which addresses the review comments
