### PR TITLE
Fix CI

### LINKED ISSUE #560: CI is currently broken on the latest nightly compiler
CI is currently broken and spits out errors like:

```
 error: the item `FifoDescriptor` is imported redundantly
  --> ipc-queue/src/fifo.rs:17:24
   |
17 | use fortanix_sgx_abi::{FifoDescriptor, WithId};
   |                        ^^^^^^^^^^^^^^
18 |
19 | use super::*;
   |     -------- the item `FifoDescriptor` is already imported here
   |
note: the lint level is defined here
  --> ipc-queue/src/lib.rs:7:9
   |
7  | #![deny(warnings)]
   |         ^^^^^^^^
   = note: `#[deny(unused_imports)]` implied by `#[deny(warnings)]`

error: the item `FifoDescriptor` is imported redundantly
 --> ipc-queue/src/interface_sync.rs:7:5
  |
7 | use fortanix_sgx_abi::FifoDescriptor;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
8 |
9 | use super::*;
  |     -------- the item `FifoDescriptor` is already imported here
```

### PR DESCRIPTION
**Pull request by raoulstrackx**
CI is currently broken due to a more intelligent nightly compiler and warnings being treated as errors. This PR fixes these errors.

Fixes #560

### CODE REVIEW

File: intel-sgx/sgxs/src/sgxs.rs [hunk 1]
```diff
@@ -418,8 +418,8 @@ impl<W: Write> SgxsWrite for W {
         let mut buf = [0u8; 64];
         unsafe {
             let (tag, headerdst) = buf.split_at_mut(8);
-            let tag = &mut *(&mut tag[0] as *mut _ as *mut u64);
-            let headerdst = &mut headerdst[0] as *mut _;
+            let tag = &mut *(&mut tag[0..8] as *mut _ as *mut u64);
```
Comment (Taowyoo) [inline intel-sgx/sgxs/src/sgxs.rs:421]: Wow, so new nightly compiler will warn this ?

**Review by Taowyoo — APPROVED** [review]

**Review by nshyrei — APPROVED** [review]

File: intel-sgx/sgxs/src/sgxs.rs [hunk 2]
```diff
@@ -418,8 +418,8 @@ impl<W: Write> SgxsWrite for W {
...
+            let headerdst = &mut headerdst[0..56] as *mut _;
```
[the remark this answers is not in the document]
Comment (raoulstrackx) [reply intel-sgx/sgxs/src/sgxs.rs:422]: It's size comes from how MRENCLAVE is being measured. See the [sgxs documentation](https://github.com/fortanix/rust-sgx/blob/master/doc/SGXS.md) and [Intel Manual vol 3D ch 36.4.1.1](https://cdrdv2.intel.com/v1/dl/getContent/671200) At the Rust code level, there isn't one an explicit type for it. Based on what's being added (`ECreate`, `Unsized`,...) different types are used.

File: intel-sgx/sgxs/src/sgxs.rs (hunk 1 above)
Comment (raoulstrackx) [reply intel-sgx/sgxs/src/sgxs.rs:421]: Yes it surprised me too!
